[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "DCU user", email = "wkx1025@foxmail.com"}]
dynamic = ["version", "description"]
